site_name: Ilker Mansur Homepage
site_url: https://ilkermansur.github.io

# Repository

repo_name: ilkermansur
repo_url: https://github.com/ilkermansur
edit_uri: ""

theme:
  name: material
  icon:
    logo: simple/commodore
  font:
    text: Roboto
    code: Source Code Pro

  features:
    - content.code.copy
    - content.code.annotate

  palette:

    # Palette toggle for light mode

    - scheme: default
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode

    - scheme: slate
      primary: green
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# for emoji

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

      # for code blocks
  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - glightbox
  - search # necessary for search to work
  - awesome-nav

extra:
  social:
    - icon: material/linkedin
      link: https://www.linkedin.com/in/ilker-mansur-1514b969/

copyright: Copyright &copy; 2025 ilkermansur